name: Deploy

permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - base
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}

    env:
      LAMBDA_NAME: born_digital_trigger
      LAMBDA_HANDLER_CODE: src/born_digital_trigger.py
      BASENAME: handle_born_digital_trigger.py

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install requirements
        run: |
            mkdir package
            python -m pip install --upgrade pip
            pip install --platform manylinux2014_x86_64 --only-binary=:all: -r requirements.txt --target ./package
            cd package
            zip -r ../${LAMBDA_NAME}.zip .
            cd ..

      - name: Make zip file
        run: |
          cp ${{ env.LAMBDA_HANDLER_CODE }} ${{ env.BASENAME }}
          zip ${{ env.LAMBDA_NAME }}.zip ${{ env.BASENAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 900
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload file to S3
        run: aws s3 cp ${{ env.LAMBDA_NAME }}.zip s3://${{ secrets.LAMBDA_BUCKET_NAME }}/${{ env.LAMBDA_NAME }}.zip

      - name: Deploy lambda package
        run: aws lambda update-function-code
          --function-name arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_LAMBDA_ACCOUNT_ID }}:function:${{ env.LAMBDA_NAME }}
          --zip-file fileb://${{ env.LAMBDA_NAME }}.zip
